### ISSUE TITLE
Cond Statements 

### ISSUE THREAD

**Issue by cpjolicoeur** [rrrene/credo#146]
[In `Credo.Check.Refactor.CondStatements` the style guide suggests](https://github.com/rrrene/credo/blob/master/lib/credo/check/refactor/cond_statements.ex) that each `cond` statement should have 3 or more clauses including the `true` clause, otherwise an `if...else` construct shoudl be used.

I'm curious the reasoning behind this style refactor suggestion?  In Elixir, `if` and `unless` are just macro expressions that become a `cond` statement anyways, so what is the reasoning behind preferring `if...else` in this case?  

Purely interested in your reasoning behind this.

**Comment by rrrene** [comment]
The idea is that your code will be easier to comprehend for many coders starting with Elixir.

But, to be honest, there is nothing wrong with writing

```elixir
    cond do
      x == y -> 0
      true -> 1
    end
```

I just think that it is "more maintainable" if written as

```elixir
    if x == y do
      0
    else
      1
    end
```

as more programmers coming from other languages won't have to think about the connotations.

But you are - as a matter of fact - giving a solid argument for not using this check. At a certain point, it is just a matter of taste. :+1:

**Comment by cpjolicoeur** [comment]
I see.  Makes sense as a gentle introduction to engineers coming into Elixir from other languages as a matter of familiarity.   My perspective was purely from knowing it's implementation under the hood.  

Thanks

**Comment by rrrene** [comment]
Just an afterthought: Implemenations change. Not too long ago the `if` macro tranformed into a `case` statement. Back then people argued to write `case` instead of `if` since it would be more explicit. Other, even more functional people argue that we should model control-flow solely via functions and pattern matching.

I would like to consider myself somewhere in between: Due to the nice macros, we can have the best of both worlds if that is what we want.

**If** you are interested in this (pun intended), there is this related article: http://michal.muskala.eu/2016/01/04/if-considered-harmful-or-is-it.html
