### ISSUE TITLE
Check all public functions have @doc

### ISSUE THREAD

**Issue by richardtylee** [rrrene/credo#158]
Is there a check for all public functions to have @doc ?

**Comment by rrrene** [comment]
No, not yet. I have another project [InchEx](https://github.com/rrrene/inch_ex), which does documentation analysis. Contrary to Credo, this tool needs the project to be compiled to load the generated documentation.

My personal plan for this feature was to wait until Credo gets a plugin system (which will happen after v1.0) and then write an InchEx plugin for Credo. 

*However*, I would merge a PR which implements the check you describe (to have the functionality today instead of sometime in the future). :+1:

**Comment by rrrene** [comment]
@richardtylee We learned through a check that checks for `@spec` annotations that there are several pitfalls with statically analysing module-attribute-based annotations for functions/modules.

I will therefore close this issue. Thx for reporting it :+1:

**Comment by lud** [comment]
Hi, 

So it means that at the moment there is no way to implement this check properly ?
