### ISSUE TITLE
Aliasing modules is an anti-feature

### ISSUE THREAD

**Issue by bbense** [rrrene/credo#2]
┃ [D] → Nested modules could be aliased at the top of the invoking module.
┃       lib/iex/server.ex:85:17 (IEx.Server.take_over)

I really don't agree with this one at all. It's stuff like this being the "default" that have largely 
put me off using Rubocop. 

I think the defaults should be things that are largely uncontroversial. Having it is fine, but 
IMHO the trade offs involved in using module aliases are huge. You'll never get universal 
consensus on any issue, but I think the tool should err on the side of caution as the default. 

I'm not sure what the right interface to all this is. Maybe checks could be tagged as  "opinionated" 
and you could have a flag like 

mix credo --full

**Comment by rrrene** [comment]
Mmmh, I see your point and the defaults are pretty much up for debate at this moment!

But, just for the sake of discussion, what are the trade-offs of using aliases? I always thought the exact opposite, but am not sure why if I read it or just assumed ... So, what are the downsides?

**Comment by bbense** [comment]
The problem is that you don't know where the function is coming from further down in the code. Your point about gathering dependencies is a good one. However, once that Alias statement scrolls off the screen that context is lost. 

If you're using an editor that has good searching tools, I'll go to a specific section of code and never see the top of the module. So if I see 

 def twitter_mentions do
┃               TwitterAPI.search(...)
┃             end

I'm going to start looking for lib/twitter_api.ex as the next file to look in and not find it.
Also, if my editor is smart enough to include IEx.Autocomplete or inline function documentation
lookup, it won't find anything about TwitterAPI. Or heck even if I have an iex -S mix command
open in another window. h TwitterAPI gets me no where. 

Now you could argue that eventually Elixir support in various tools will get good enough so all 
the above scenerios will just work. But that's not today.

**Comment by rrrene** [comment]
Agreed. My idea for the "Software Design" category was that these are merely suggestions and less concering than issues from, for example, the "Warning" category.

To your point: 

There is the concept of "issue priority" in Credo (note-to-self: I have to explain that in more detail in the README), where low priority issues are not shown in the standard report generated by `mix credo`. An example for such a low priority issue is `MaxLineLength`, because I found it superficially hard to constrain pattern matches in function signatures to 80 characters and so do Èlixir, Ecto, Plug, and many others.

I am mentioning this because this might be a solution akin to your `mix credo --full` suggestion: We could set the `AliasUsage` check to low priority, so it will not show by default. But you can show all issues including the low priority ones with a command-line switch (currently named `--pedantic`, will rename to `--all-priorities` in the next release to be more clear).

What do you think?

**Comment by bbense** [comment]
That sounds great.

**Comment by rrrene** [comment]
`v0.1.6` contains both changes we discussed here. Thx again! :+1:
