### ISSUE TITLE
Proposal: Add `--no-color` to prevent ANSI coloring of output

### ISSUE THREAD

**Issue by rrrene** [rrrene/credo#219]
Although Credo's color rich interface is one of its most obvious selling points, it might be beneficial to have an option to supress the ANSI coloring of the results.

**Comment by NobbZ** [comment]
I wanted to file exactly this issue right now. The ansi stuff makes it hard to mentally parse the output on windows terminals...

**Comment by sstern6** [comment]
@rrrene wouldnt mind taking this on, is there a currently implemented switch for Ansi coloring?

Correct me if I am wrong, but isnt this coloring coming from `Bunt`?

Found delegations for Bunt here `defmodule Credo.CLI.Output.UI`.  Could you give me a push in the right direction and Ill get on it.

Thanks

**Comment by rrrene** [comment]
That's correct. The challenge here seems to be that the question "should I color this?" can only be answered by the config object. So we have two options: keep global state based on the config setting or passing the `%Config{}` struct to the `UI.puts` call.

The second solution sounds cleaner to me, but also sounds like it would be much more work (because *every* call would have to pass the config).

**Comment by sstern6** [comment]
Thanks for the guidance, but it shouldn't be that much more work for the second challenge, just need to include the config, check the switch value, then if the switch value is true, keep functionality the same, else replace Bunt.puts with IO.puts..............i think 😄 ?

Also, it doesnt make me comfortable  keeping global state like that, Id rather spend the time making it clean.  Especially with all of the new feature requests, might be worth the investment.

**Comment by niahoo** [comment]
Maybe you should just check the environment at compile time and do not `defdelegate` to `Bunt` but to `IO` ?

Is it possible ?

**Comment by rrrene** [comment]
@niahoo Thanks for your input. Unfortunately, this is not a feasable solution, since compile-time is ... well ... compile-time. If you Credo with `--no-color` the first time, it would be colorless until recompiled by force. 😞

**Comment by niahoo** [comment]
Sure, and that is okay because if you do not have colors on windows, you will not have them ht next time you recompile your project wehn coding (5 min later).

But if you want colors and find a way to have them on windows, then force recompile credo is easy. That's a one time operation.

**Comment by rrrene** [comment]
I misread your initial comment. Sorry. 😞 

Would appreciate a pull request for the functionality you describe! :+1:

**Comment by NobbZ** [comment]
Well... I am switching around a windows shell (aka cmd.exe), a powershell, a git bash and a msys2 bash more or less randomly. 2 of them do understand ANSI-Colors, 2 do not.

I do enjoy having colors in the ones that do understand them, but I do hate the garbage characters created by ANSI stuff in the windows terminals.

Since I do switch around between them very often and don't want to recompile everytime, I'd prefer to have a solution which does not require recompilation, but works with either an on/off-switch (`--(no-)color`), works with an ENV-var, or does a proper check if the environment is capable of ANSI.

But I think the last one were better placed in `bunt`, so one can just use `bunt` and it decides what to do. Perhaps even make it overridable via mix-config, ENV-vars or what ever one likes?

**Comment by niahoo** [comment]
Yeah, I think it would be cleaner if bunt is aware of the ability of the shell to display colors and maybe ignore them. That's not a thing that credo should do. Credo should say "paint some red here", and bunt should say "ok" then ignore it.

**Comment by NobbZ** [comment]
I did not delve into it, but according to https://elixirforum.com/t/unable-to-colorize-escript-text-output/2563 it seems that `bunt` does already respect the return value of [`IO.ANSI.enabled?/0`](http://elixir-lang.org/docs/stable/elixir/IO.ANSI.html#enabled?/0), which itself is configurable by the key `:ansi_enabled` in application `:elixir`, perhaps we can alter that setting on presence of `--(no-)color` in credo?

**Comment by rrrene** [comment]
@NobbZ I saw that as well when looking into this. 

But isn't it strange that ANSI isn't deactivated through [`IO.ANSI.enabled?/0`](http://elixir-lang.org/docs/stable/elixir/IO.ANSI.html#enabled?/0) in your Windows shell?

**Comment by NobbZ** [comment]
Well, as you ask for it... I can only check at my office-workstation, and here it does in fact return `false` in an iex session in cmd, powershell and git bash.

But still I do get ANSIfied output of credo in each of them.

Since I will attend to a talk this evening ;) and also still have some tickets to close at work, I will not have time to prepare a sample project before thursday evening. But I do have some OSS project which does show the problem at least at my office-workstation, I am not quite sure if it is on my private laptop as well. https://gitlab.com/NobbZ/irc_ex

This project does show some weird characters at the windows terminal which I do assume to be mangled ANSI-codes, but also it does not show any colors at all in a git bash.

**Comment by niahoo** [comment]
I had the same results : `IO.ANSI.enabled?/0` is `false` but I have ANSI tokens in the shell output. But, for instance, `npm` displays colors with no problem.

**Comment by NobbZ** [comment]
Last night I had some kind of flashback...

Currently there is rrrene/inch_ex#23, maybe there is some relationship behind the weird characters?

But in inch's output I do get (some) colors... Weird... 

![credo_inch](https://cloud.githubusercontent.com/assets/58951/20792224/fc3eb66c-b7c0-11e6-9993-feed4d790407.png)

In git-bash I do get full colors in inch_ex, but there are no weitrd characters (except that I do get "ä" instead of bar chars, but I do assume that is because of the usual windows encoding stuff...)

**Comment by rrrene** [comment]
Added on `master`, `v0.6.0` will be released soon.
