### ISSUE TITLE
Suggestion: Do not check for @moduledoc and @doc if the extension is .exs

### ISSUE THREAD

**Issue by josevalim** [rrrene/credo#222]
Today the moduledoc and doc checks runs on all files except some cases based on the module name. However, instead of checking the module name, I think it would be better if credo disable the warning based on the extension.

In particular, .exs files are never compiled, which means their documentation is never accessible, which means their doc/moduledoc attributes are irrelevant.

If we do such, there is no need to blacklist module names such as the ones ending with Test (which could have false negatives)!

**Comment by rrrene** [comment]
I am all for the idea of using the file extension :+1: but I do not think we should get rid of the regular expression. The reason is that I do not have a better solution to avoid Phoenix projects triggering issues.

In some cases, like controllers and sockets, I could see an argument for people to document these or at least explicitly not document them via `@moduledoc false`. But I do not want to report an issue for undocumented endpoints, routers and repos *on default*.

Thoughts?

**Comment by josevalim** [comment]
Oh, sorry if i was not clear. Yes, we should not get rid of the Regex. It will help clean the Regex though!

**Comment by rrrene** [comment]
Absolutely!
