### ISSUE TITLE
Proposal: prefer implicit try in functions

### ISSUE THREAD

**Issue by michalmuskala** [rrrene/credo#224]
A useful, but little known feature of elixir is the implicit `try` that is placed around things like `def`, and also some other macros that create functions, like `test` from ExUnit.

For example, the two functions below are equivalent:
```elixir
def format(value) do
  try
    do_format(value)
  catch
    :exit, reason -> {:error, reason}
  end
end

def format(value) do
  do_format(value)
catch
  :exit, reason -> {:error, reason}
end
```

I believe this is a beneficial transformation simplifying code and decreasing nesting. Additionally this check should be fairly easy to detect - when the function's body is a single try expression.

**Comment by NobbZ** [comment]
You say this feature is little known. Well maybe. It looks cool to have
this but is this feature documented or were this abusing an implematation
detail which could get changed any time?

Michał Muskała <notifications@github.com> schrieb am Fr., 11. Nov. 2016
18:37:

**Comment by michalmuskala** [comment]
This is a feature that is part of the language and is not going anywhere. It's used in elixir itself as well as in the "core" projects like ecto, phoenix, etc.

**Comment by NobbZ** [comment]
I just have seen elixir-lang/elixir#5442, so yes it seems to be a very official feature, thank you!

**Comment by fishcakez** [comment]
Implicit `try` changes the meaning of code prior to its definition:

```elixir
def fun() do
# code here
after
  # adding implicit try, which might be missed if only reading the herad of the function
end
```

I think this warning should be off by default.

**Comment by jeremyjh** [comment]
What bothers me about this topic is that in elixir-lang/elixir#5442 Elixir core team decided to make this feature less discoverable per Jose's suggestion of not cross-referencing it in try, but only in def. Either this is a good feature that should be promoted or its a special-case and as Fish says, should be only a consistency check.

**Comment by nietaki** [comment]
When I stumbled upon the "implicit try" in our codebase I was surprised that it's a thing, especially since I couldn't find it referenced in anywhere in the language docs (now I know it's in https://hexdocs.pm/elixir/Kernel.html#def/2 , where I was also looking for it in `try` docs).

In principle, I don't think using Credo's default settings to enforce the usage of syntax sugar and implicit constructs over explicit ones is a good direction in general and it seems like some comments in this issue and https://github.com/elixir-lang/elixir/pull/5441 reflect this sentiment.
