### ISSUE TITLE
0 mods/funs, found nothing

### ISSUE THREAD

**Issue by jessejanderson** [rrrene/credo#24]
I'm new to Elixir (and relatively new to programming in general) so I might be missing something obvious, but when I run `mix credo` I get a result of `Checking 4 source files` and then `0 mods/funs, found nothing.`

Is there something else I need to be doing to get this to work?

**Comment by rrrene** [comment]
Hi there,

what do you get get when you run

    mix credo --strict

?

**Comment by jessejanderson** [comment]
`mix credo --strict` gives me the same thing.

Someone in the Elixir Slack suggested `mix credo suggest -A -a` and that gave me results. `-A` seems to have been the missing link as running `mix credo -A` gives me what I expected to see.

Is there a reason the normal `mix credo` would be saying nothing found? The `0 mods/funs, found nothing` message was a little misleading as it sounded like it wasn't able to find my functions.

**Comment by rrrene** [comment]
You touch on two issues here:

1. `--strict` is/should be an alias for `-A` (which is an alias for `--all-priorities`), so I am not sure why it behaves incorrectly here. Is the code you are testing this on on GitHub?
2. the output "0 mods/funs, found nothing." does not make sense in most situations, because it means one of three things 
    (a) you have no issues, 
    (b) you have issues, but they are low priority,
    (c) no files were detected.

In each of those situations we could do better than "0 mods/funs, found nothing.". I will fix this and prepare a release on the weekend!

**Comment by jessejanderson** [comment]
Awesome!

Just pushed my code, it was just a sample from the Programming Elixir book and I was wanting to see how Credo worked.
https://github.com/jessejanderson/programming-elixir-issues

**Comment by rrrene** [comment]
Hi, `v0.2.4` contains new wording, which I hope is "good enough". Be sure to update the version requirement to `~> 0.2`

Thanks for your help. We should certainly keep an eye on the "understandability" of what the user sees! :+1:
