### ISSUE TITLE
Incorrect space around operators warning in pipe

### ISSUE THREAD

**Issue by chrismcg** [rrrene/credo#46]
```elixir
  def to_timestamp(datetime) do
    datetime
    |> :calendar.datetime_to_gregorian_seconds
    |> -(@epoch)
  end
```

I get the `There are spaces around operators most of the time, but not here.` report for the last line of the pipeline.

**Comment by rrrene** [comment]
I took a day to answer this as I was recovering from the fact that you can pipe into arithmetic operations (although it makes perfect sense). Personally, I do not think this is something that should be widely used since it is really confusing (I first thought `-(@epoch)` was a negated numerical value, not an operation).

That said, since this is an operation like `x - @epoch`, why don't you write it like this:

```elixir
  def to_timestamp(datetime) do
    datetime
    |> :calendar.datetime_to_gregorian_seconds
    |> - @epoch
  end
```

I only tested this in IEX, so maybe I missed something?

**Comment by chrismcg** [comment]
That's a really good point... We need some kind of term for "overpiping". I converted it to

`:calendar.datetime_to_gregorian_seconds(datetime) - @epoch`

Which is much clearer anyway!
