### ISSUE TITLE
Server mode

### ISSUE THREAD

**Issue by hauleth** [rrrene/credo#473]
Running Mix tasks is quite heavy (at least 1s on my machine) and while for infrequent commands like `mix ecto.migrate` or similar it isn't big problem then for listing it can become quite troublesome, especially when you want to run lint on each edit/save then it becomes quite problematic. Solution could be running Credo as long running server that would implement some kind communication protocol that would allow linting files without costly startup of Erlang VM each time when it is needed.

**Comment by NobbZ** [comment]
Such a server could also memorize earlier runs and results for consistency checks. In the context of the server we could scan only the changed file and still have it checked for consistency with the project since we actually know already how the rest of the project is formatted.

This would give another plus on speed.

**Comment by KronicDeth** [comment]
elixir-lang/elixir#949 is related to `mix credo` spiking the CPU when I run it to annotate the open file.  Having the server support running the whole file, and then retaining enough state to quickly report the full details for any one line would be helpful as that's how I'm using it now, so that I can annotate each flyweight result with the full explanation.

**Comment by rrrene** [comment]
Credo 1.5 provides both an interface for running Credo programmatically as well as incrementally. It has only taken three years ;-)
