### ISSUE TITLE
Color scheme readability

### ISSUE THREAD

**Issue by achempion** [rrrene/credo#728]
### Environment

* Credo version 1.1.4
* Erlang/Elixir version 1.9.4
* Operating system: mac os catalina
* Terminal Emulator iterm

```sh
ZSH_THEME="robbyrussell"
```

### What were you trying to do?

I find the color theme is quite hard to read in terminal. Especially for `(1 more, use `-a` to show them)` line. I guess it because of faint blue and my color scheme in terminal.

https://github.com/rrrene/credo/blob/c602f78c2f231f5abe34a178a2ed4b829d2c40d0/lib/credo/cli/command/suggest/output/default.ex#L134

![Screenshot 2019-12-15 at 08 54 19](https://user-images.githubusercontent.com/1409852/70858739-d9aea900-1f18-11ea-80d8-9bf6230ac9f1.png)

**Comment by NobbZ** [comment]
Perhaps contrast were better if you had an opaque terminal rather than a transparent one?

I never had any problems reading the output on my white on black setting.

**Comment by rrrene** [comment]
@achempion Thx for reporting this. Credo should be approachable and I take concerns regarding this very seriously. But what makes we wonder is the fact that the "blue" of "6 code readability issues" is barely readable as well and that is just "blue" (neither faint nor bright).

Regarding nobbz's suggestion: Is this a Catalina standard terminal (with the half transparent background)?

**Comment by achempion** [comment]
I'm using `iterm` which is somewhat popular among the mac users.

 I've made a transparency to 0 and switched to the default color scheme. On that point I'm quite unsure either it is iterm's issue of credo's.

![Screenshot 2019-12-15 at 21 47 30](https://user-images.githubusercontent.com/1409852/70867293-ed8ff480-1f84-11ea-9ddd-c20101cc54a0.png)

**Comment by rrrene** [comment]
Credo mostly uses the eight standard ANSI color shown in your preferences.

I am absolutely open to tweaking the colors, I'm just not sure if we always put someone else at a disadvantage when deviating from these 8 standard colors, since you can configure those in any terminal and most terminal themes configure them in a less ... unfortunate way (IMHO everything in blue would be sub-optimal to read with that shade of blue written on black).

**Comment by OvermindDL1** [comment]
> Credo mostly uses the eight standard ANSI color shown in your preferences.

Please don't deviate from these, it's extremely readable in my terminal.  ^.^

**Comment by cybrox** [comment]
I support the idea of sticking to the standard ANSI colors. It's a pain that a lot of popular themes and styles configure these colors so terribly wrong but I appreciate having to change them once in my terminal configuration instead of having to fiddle with every individual tool - like credo - to get readable output on my terminal.

**Comment by achempion** [comment]
Thank you all for the feedback, I'll consider to open an issue for the iterm to adjust the default color theme.
