### ISSUE TITLE
Allow for custom operators in the PipeChainStart check

### ISSUE THREAD

**Issue by NorthIsUp** [rrrene/credo#740]
### Environment

* Credo version (`mix credo -v`): 1.1.0
* Erlang/Elixir version (`elixir -v`): 1.8.2 OTP-22
* Operating system: MacOS 10.15.2

### What were you trying to do?

Use [brex result](https://hexdocs.pm/brex_result/readme.html) in a pipeline.

Brex Result adds the `~>` operator that is "pipeline-like". It does a bunch of nice things around dealing with ok/error tuples.

for example
```
def something(payload, version) do
    payload
    |> Jason.encode()
    ~> encode(version)
    |> case do
      {:ok, token} -> {:ok, token}
      {:error, reason} -> {:error, reason}
      :error -> {:error, :unknown_error}
    end
end
```

### Expected outcome

One should be able to add custom "start pipeline" atoms to the Credo.Check.Refactor.PipeChainStart config.

### Actual outcome

the current config options don't allow for this.

Not 100% sure here, but when trying to figure out why it seems that the `to_function_call_name` has a regex that swallowed the fact that `~>` is a function that should be considered.

**Comment by TheFirstAvenger** [comment]
1) I believe the way to tackle this would be to add additional versions of the two `traverse({:|>, ...` functions that do the same except have `:~>` instead of `:|>` in their header.
2) My guess is that this won't make it into core credo as this is not standard Elixir. It would, however, be a good use case for a custom check which users of brex can add and disable the core version.
3) If you do still want to propose it being added to core Credo, could you please close this issue and submit it here: https://github.com/rrrene/credo-proposals

**Comment by rrrene** [comment]
@NorthIsUp @fuelen Thanks for reporting this 😀  It is now fixed on `master`.

You can try this by setting the Credo dep to

```elixir
{:credo, github: "rrrene/credo"}
```

Please report back if your issue is solved! 👍

**Comment by fuelen** [comment]
It works :+1:

**Comment by rrrene** [comment]
Forgot to close the issue: `v1.5.4` includes this fix 👍
