### ISSUE TITLE
Diff is checking files that weren't changed

### ISSUE THREAD

**Issue by Ch4s3** [rrrene/credo#844]
### Environment

* Credo version (`mix credo -v`): `1.5.4`
* erlang; `23.1.5`
* elixir: `1.11.2-otp-23`
* Operating system: ubuntu:20.04 ci and MacOS 10.14.6 locally

### What were you trying to do?
In ci I'm running `mix credo diff master --config-name default -a` and it shows issues from files that aren't in the diff.
Ci is running ubuntu:20.04.

### Expected outcome
I would expect to not see any issues, as none of the files are changed by my branch.

### Actual outcome
In CI I'm seeing errors that aren't in the diff. In both places, I'm seeing the following.
`Diffing 710 source files in working dir with master (this might take a while) ...`

**Comment by rrrene** [comment]
I pushed a fix to branch `release/1.5` that might be relevant here, where the base branch was always analyzed using `--strict` which led to some weird results, just like the one you're describing.

Can you test again using that branch?

**Comment by Ch4s3** [comment]
> I pushed a fix to branch `release/1.5` that might be relevant here, where the base branch was always analyzed using `--strict` which led to some weird results, just like the one you're describing.
> 
> Can you test again using that branch?

I'll check later today and get back to you.

**Comment by Ch4s3** [comment]
I got someone else on out team to try it, and the results were the same.

**Comment by DavidAntaramian** [comment]
I work on the same codebase as Chase. Our goal is that Credo should only evaluate files modified by commits in the current branch that aren't in `master`—since there's a large number of existing deficiencies, this helps us progressively clean up deficiencies when an engineer is already working on the file.

As Chase mentioned, the command we run in CI is:

```
mix credo diff master --config-name default -a
```

What I _believe_ is happening based on the symptoms we're seeing, is that Credo is flagging files that have changed in _either_ the `master` branch _or_ the current branch. So if there are commits in `master` that aren't in the current branch, it will evaluate the files changed in those commits for Credo checks—but in the current branch, those files won't have the Credo fixes that have been merged to `master`, causing the Credo check to fail.

I haven't been able replicate the issue locally, though. This could be a misunderstanding on our part of how to properly call `mix credo` to accomplish our goal 😓 

Our current work-around is for team members to either rebase or merge in changes from the `master` branch to get CI to pass.

**Comment by rrrene** [comment]
So let's suppose your repo's commit history looks like this:

```
base  -  A  -  B  -  C  -  D   (master)
                \
                 \-  X  -  Y  -  Z   (current-branch)
```

What I understand is that we are on `current-branch` and we want to see the issues since commit `B` . But instead you see all issues introduced by `C` and `D` as well (i.e. issues from changes that were added on `master` in the meantime).

Is this correctly describing the problem?

**Comment by DavidAntaramian** [comment]
Correct: we are on `current-branch` and we want to see the issues since commit `B`.

Just to give a full picture, let's suppose a slightly more complex commit history:

```
 (feature-a)                         J---K---L     
                                    /         \
 (master)           base---A---B---C---D---E---F  
                                \
 (current-branch)                X---Y---Z         
```

Assume that:
  - At commit `A`, there exists some file `lib/app/advertising.ex` that does not pass Credo checks
  - Merging to `master` after `A` is only allowed if running `mix credo diff master --config-name default -a` on the branch to be merged passes
  - In branch `feature-a`, changes to `lib/app/advertising.ex` are introduced.
  - At commit `F`, `lib/app/advertising.ex` now passes Credo checks, since that was required in order to merge the commits from `feature-a` into `master`.

Now, commits `X`, `Y`, and `Z` do _not_ touch `lib/app/advertising.ex`. However, when `mix credo diff master --config-name default -a` is run on `current-branch`, it will show errors for `lib/app/advertising.ex`. The Credo errors are based on the file's state in the branch, even though it hasn't been changed in the branch.

I keep thinking we either have the wrong expectations of the command or we're using it incorrectly.

**Comment by rrrene** [comment]
> The Credo errors are based on the file's state in the branch, even though it hasn't been changed in the branch.

That makes a lot of sense. This gets us closer to what is wrong with the `diff` command in this instance.

Could you try running this command on your CI?

```
mix credo diff `git merge-base master HEAD`
```

This should run `mix credo diff`  from the point from which your feature branched off ( `B` in our example).

**Comment by DavidAntaramian** [comment]
Brilliant! That appears to have solved it.

So the parameter to `diff` is the git ref that we want to compare against? That makes sense and explains why using `master` caused such confusion.

**Comment by rrrene** [comment]
The shorthand `mix credo diff <REF>` behaves similar to `git diff <REF>`. It basically runs Credo against `<REF>` and against your working tree and tells you the difference from Credo's perspective.


It's great that it works now 👍  Although I think that this should be less confusing and require less Git-fu on the user's part.

Credo's next update will provide additional, more "descriptive" options to differentiate use cases:

```
mix credo diff --from-git-ref <REF> # behaves like the current shorthand `mix credo diff <REF>`
mix credo diff --from-git-merge-base <REF> # this would have had you covered, if it had already existed
mix credo diff --from-dir <PATH> # allows you to diff using other VCS besides Git
```

**Comment by rrrene** [comment]
This is part of v1.6.1 💚
