### ISSUE TITLE
Credo.Check.Readability.Specs disabled by default without being documented as such

### ISSUE THREAD

**Issue by josef-bolt** [rrrene/credo#922]
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here

### Environment

* Credo version (`mix credo -v`): 1.6.0
* Erlang/Elixir version (`elixir -v`): Elixir 1.12.3 (compiled with Erlang/OTP 22)
* Operating system: MacOS

### What were you trying to do?

Use Credo for detecting public functions without typespecs.

### Expected outcome

Results for missing typespecs.

### Actual outcome

No results for missing typespecs. I have resolved this by running `mix credo --enable-disabled-checks specs --all --checks specs` . It seems like this feature is disabled by default - but I couldn't find anything about this anywhere in the docs. Happy to put out a small PR updating the docs [here](https://hexdocs.pm/credo/Credo.Check.Readability.Specs.html#content) if that's the correct place for it.

**Comment by rrrene** [comment]
There is currently no documentation on which checks are enabled by default and which are not.

You can refer to the [`:disabled` section of the config](https://github.com/rrrene/credo/blob/b9d99da01b8c9a881d7ade5630c553623d31b503/.credo.exs#L161) to see checks are disabled by default.

Maybe we should document this in a more obvious fashion.

Please also note that all disabled checks are disabled for a reason (they are either controversial or experimental). The check you are referering to simply does not work in all situations since it does work off of the compiled `.beam` files but rather does a static analysis of the source code (as does all of Credo).
